using System;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace blogproject.Data
{
    public class AuthDbContext : IdentityDbContext //inhertis it from the nuget pakage
    {
        public AuthDbContext(DbContextOptions options) : base(options)
        {

        }

        protected override void OnModelCreating(ModelBuilder builder) //autogenerated override
        {
            base.OnModelCreating(builder);

            //seed the roles

            //seed superadmin user

            //Add all the roles to superadminuser
        }
    }
}

